on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: pwd && dotnet pack ./CraveInjectables.SqlDataService/CraveInjectables.SqlDataService.csproj --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push CraveInjectables.SqlDataService.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${Nuget_Token}
      env:
        Nuget_Token: ${{ secrets.NUGET_API_KEY}}